'use client'

import { useState, useEffect, useRef } from 'react'
import type { Question } from '@/types/database'
import { SUBJECTS, DIFFICULTIES, MISTAKE_REASONS } from '@/types/database'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  MoreVertical,
  Edit,
  Trash2,
  CheckCircle,
  RefreshCw,
  Eye,
  Brain,
  Copy,
  Loader2,
  ThumbsUp,
  ThumbsDown,
  Bookmark,
  X,
} from 'lucide-react'
import { useDeleteQuestion, useReviewQuestion, useMasterQuestion, useAnalyzeMistake, useGenerateVariations, useUpdateQuestion } from '@/hooks/useQuestions'
import { useCollectVariation, useFeedbackVariation, useAIGeneratedQuestions, useDeleteVariation } from '@/hooks/useAIGeneratedQuestions'
import { formatDistanceToNow } from '@/lib/utils'
import { QuestionImageManager } from './QuestionImageManager'

interface QuestionCardProps {
  question: Question
  onEdit?: (question: Question) => void
  onView?: (question: Question) => void
  selected?: boolean
  onSelectionChange?: (question: Question, selected: boolean) => void
}

export function QuestionCard({
  question,
  onEdit,
  onView,
  selected = false,
  onSelectionChange,
}: QuestionCardProps) {
  const [showAnswer, setShowAnswer] = useState(false)
  const [showVariations, setShowVariations] = useState(false)
  const [localAnalysis, setLocalAnalysis] = useState<{
    tags: string[]
    detail: string
    advice: string
  } | null>(null)
  const [expandedVariationId, setExpandedVariationId] = useState<string | null>(null)
  const autoGeneratedRef = useRef(false)

  // 错因分析手动编辑状态
  const [isEditingAnalysis, setIsEditingAnalysis] = useState(false)
  const [editingTags, setEditingTags] = useState<string[]>([])
  const [editingDetail, setEditingDetail] = useState('')
  const [editingAdvice, setEditingAdvice] = useState('')
  const [customTagInput, setCustomTagInput] = useState('')

  // 举一反三目标难度
  const [variationDifficulty, setVariationDifficulty] = useState<'same' | 'easier' | 'harder' | 'mixed'>('same')

  const deleteQuestion = useDeleteQuestion()
  const reviewQuestion = useReviewQuestion()
  const masterQuestion = useMasterQuestion()
  const analyzeMistake = useAnalyzeMistake()
  const generateVariations = useGenerateVariations()
  const updateQuestion = useUpdateQuestion()
  const collectVariation = useCollectVariation()
  const feedbackVariation = useFeedbackVariation()
  const deleteVariation = useDeleteVariation()
  const {
    data: historicalVariations,
    isLoading: isLoadingVariations,
  } = useAIGeneratedQuestions(showVariations ? question.id : null)

  // 获取学科和难度的中文显示
  const subjectLabel = SUBJECTS.find((s) => s.id === question.subject)?.label || question.subject
  const difficultyLabel = DIFFICULTIES.find((d) => d.id === question.difficulty)?.label || question.difficulty
  const difficultyColor = {
    easy: 'bg-[#d1fae5] text-[#10b981] border-[#10b981]/30',
    medium: 'bg-[#fef3c7] text-[#f59e0b] border-[#f59e0b]/30',
    hard: 'bg-[#ffe4e6] text-[#f43f5e] border-[#f43f5e]/30',
  }[question.difficulty]

  const handleDelete = () => {
    if (confirm('确定要删除这道题目吗？')) {
      deleteQuestion.mutate(question.id)
    }
  }

  const handleReview = () => {
    reviewQuestion.mutate(question.id)
  }

  const handleMaster = () => {
    if (question.is_mastered) {
      return
    }
    masterQuestion.mutate(question.id)
  }

  const handleAnalyze = async () => {
    const result = await analyzeMistake.mutateAsync(question.id)
    setLocalAnalysis(result.analysis)
  }

  const handleGenerateVariations = () => {
    setShowVariations(true)
  }

  const handleRegenerateVariations = () => {
    generateVariations.mutate({ id: question.id, count: 3, difficulty: variationDifficulty })
  }

  const handleOpenAnalysisEdit = () => {
    setEditingTags(existingAnalysis.tags)
    setEditingDetail(existingAnalysis.detail || '')
    setEditingAdvice(existingAnalysis.advice || '')
    setCustomTagInput('')
    setIsEditingAnalysis(true)
  }

  const toggleEditingTag = (tag: string) => {
    setEditingTags((prev) =>
      prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag]
    )
  }

  const addCustomTag = () => {
    const tag = customTagInput.trim()
    if (!tag) return
    if (editingTags.includes(tag)) return
    setEditingTags((prev) => [...prev, tag])
    setCustomTagInput('')
  }

  const removeEditingTag = (tag: string) => {
    setEditingTags((prev) => prev.filter((t) => t !== tag))
  }

  const handleSaveAnalysis = () => {
    updateQuestion.mutate(
      {
        id: question.id,
        data: {
          mistake_reason: editingTags.length > 0 ? editingTags : null,
          mistake_reason_detail: editingDetail || null,
          mistake_reason_advice: editingAdvice || null,
        },
      },
      {
        onSuccess: () => {
          setLocalAnalysis({
            tags: editingTags,
            detail: editingDetail,
            advice: editingAdvice,
          })
          setIsEditingAnalysis(false)
        },
      }
    )
  }

  // 当展开举一反三面板时，若历史为空且尚未手动生成过，则自动调用 AI 生成
  useEffect(() => {
    if (
      showVariations &&
      !isLoadingVariations &&
      historicalVariations &&
      historicalVariations.length === 0 &&
      !generateVariations.isPending &&
      !autoGeneratedRef.current
    ) {
      autoGeneratedRef.current = true
      generateVariations.mutate({ id: question.id, count: 3, difficulty: variationDifficulty })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showVariations, isLoadingVariations, historicalVariations, generateVariations.isPending, question.id, variationDifficulty])

  // 关闭弹框时重置自动生成标记，下次打开可再次触发
  useEffect(() => {
    if (!showVariations) {
      autoGeneratedRef.current = false
    }
  }, [showVariations])

  // 展示的数据以服务端查询为准（重新生成后会刷新历史列表）
  const displayedVariations = historicalVariations || []
  const hasHistoricalVariations = displayedVariations.length > 0

  const existingAnalysis = localAnalysis || {
    tags: question.mistake_reason || [],
    detail: question.mistake_reason_detail,
    advice: question.mistake_reason_advice,
  }

  const hasAnalysis = existingAnalysis.tags.length > 0

  return (
    <div className="bg-white rounded-lg border border-[#dee5eb] shadow-sm hover:shadow-md transition-shadow p-4">
      {/* 头部：标签和操作 */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex flex-wrap gap-2">
          {onSelectionChange && (
            <label className="flex cursor-pointer items-center gap-2 rounded border border-[#dee5eb] px-2 py-1 text-xs text-[#626a72]">
              <input
                type="checkbox"
                checked={selected}
                onChange={(event) => onSelectionChange(question, event.target.checked)}
                className="h-4 w-4 accent-[#0070a0]"
              />
              选入复习卷
            </label>
          )}
          <Badge variant="outline" className="bg-[#cce5f3] text-[#0070a0] border-[#0070a0]/30">
            {subjectLabel}
          </Badge>
          <Badge variant="outline" className={difficultyColor}>
            {difficultyLabel}
          </Badge>
          {question.is_mastered && (
            <Badge variant="outline" className="bg-[#d1fae5] text-[#10b981] border-[#10b981]/30">
              <CheckCircle className="w-3 h-3 mr-1" />
              已掌握
            </Badge>
          )}
        </div>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
              <MoreVertical className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={() => onView?.(question)}>
              <Eye className="w-4 h-4 mr-2" />
              查看详情
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleReview}>
              <RefreshCw className="w-4 h-4 mr-2" />
              记录复习
            </DropdownMenuItem>
            {!question.is_mastered && (
              <DropdownMenuItem onClick={handleMaster}>
                <CheckCircle className="w-4 h-4 mr-2" />
                标记掌握
              </DropdownMenuItem>
            )}
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={handleAnalyze} disabled={analyzeMistake.isPending}>
              <Brain className="w-4 h-4 mr-2" />
              {analyzeMistake.isPending ? '分析中...' : hasAnalysis ? '重新分析错因' : 'AI 错因分析'}
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleGenerateVariations} disabled={generateVariations.isPending}>
              <Copy className="w-4 h-4 mr-2" />
              {generateVariations.isPending ? '生成中...' : '举一反三'}
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={() => onEdit?.(question)}>
              <Edit className="w-4 h-4 mr-2" />
              编辑
            </DropdownMenuItem>
            <DropdownMenuItem
              onClick={handleDelete}
              className="text-[#f43f5e] focus:text-[#f43f5e]"
            >
              <Trash2 className="w-4 h-4 mr-2" />
              删除
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      {/* 题目内容 */}
      <div className="mb-3">
        <p className="text-sm text-[#626a72] mb-1">{question.category}</p>
        <p className="text-[#1f1f1f] whitespace-pre-wrap">{question.content}</p>
      </div>

      <QuestionImageManager key={`${question.id}-${question.images?.map((image) => image.id).join('-') || 'legacy'}`} question={question} />

      {/* 答案区域 */}
      <div className="border-t border-[#dee5eb] pt-3 mb-3">
        <div className="flex flex-wrap gap-2 mb-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setShowAnswer(!showAnswer)}
            className="text-[#0070a0] hover:text-[#004968]"
          >
            {showAnswer ? '隐藏答案' : '显示答案'}
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleAnalyze}
            disabled={analyzeMistake.isPending}
            className="text-[#0070a0] hover:text-[#004968]"
          >
            {analyzeMistake.isPending ? (
              <>
                <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                分析中...
              </>
            ) : (
              <>
                <Brain className="w-4 h-4 mr-1" />
                {hasAnalysis ? '重新分析错因' : 'AI 错因分析'}
              </>
            )}
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleGenerateVariations}
            disabled={generateVariations.isPending}
            className="text-[#0070a0] hover:text-[#004968]"
          >
            {generateVariations.isPending ? (
              <>
                <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                生成中...
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 mr-1" />
                举一反三
              </>
            )}
          </Button>
        </div>

        {showAnswer && (
          <div className="mt-2 space-y-2">
            <div>
              <p className="text-sm font-medium text-[#626a72]">正确答案：</p>
              <p className="text-[#1f1f1f] bg-[#d1fae5]/30 p-2 rounded">
                {question.answer}
              </p>
            </div>

            {question.user_answer && (
              <div>
                <p className="text-sm font-medium text-[#626a72]">我的答案：</p>
                <p className="text-[#1f1f1f] bg-[#ffe4e6]/30 p-2 rounded">
                  {question.user_answer}
                </p>
              </div>
            )}

            {question.explanation && (
              <div>
                <p className="text-sm font-medium text-[#626a72]">答案解析：</p>
                <p className="text-[#626a72] bg-[#cce5f3]/30 p-2 rounded whitespace-pre-wrap">
                  {question.explanation}
                </p>
              </div>
            )}
          </div>
        )}

        {/* 错因分析结果 */}
        {hasAnalysis && (
          <div className="mt-3 bg-[#f7f9fa] border border-[#dee5eb] rounded-lg p-3">
            <div className="flex items-center justify-between gap-2 mb-2">
              <div className="flex items-center gap-2">
                <Brain className="w-4 h-4 text-[#0070a0]" />
                <p className="text-sm font-medium text-[#1f1f1f]">AI 错因分析</p>
              </div>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleOpenAnalysisEdit}
                disabled={updateQuestion.isPending}
                className="h-7 px-2 text-[#626a72] hover:text-[#0070a0]"
              >
                <Edit className="w-3.5 h-3.5 mr-1" />
                编辑
              </Button>
            </div>
            <div className="flex flex-wrap gap-1 mb-2">
              {existingAnalysis.tags.map((tag) => (
                <Badge key={tag} variant="outline" className="text-xs bg-[#ffe4e6] text-[#f43f5e] border-[#f43f5e]/30">
                  {tag}
                </Badge>
              ))}
            </div>
            <p className="text-sm text-[#1f1f1f] mb-1">{existingAnalysis.detail}</p>
            <p className="text-sm text-[#626a72]">
              <span className="font-medium">建议：</span> {existingAnalysis.advice}
            </p>
          </div>
        )}
      </div>

      {/* 举一反三弹框 */}
      <Dialog open={showVariations} onOpenChange={setShowVariations}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Copy className="w-5 h-5 text-[#0070a0]" />
              举一反三
              {hasHistoricalVariations && historicalVariations && (
                <Badge variant="outline" className="text-xs bg-[#d1fae5] text-[#10b981] border-[#10b981]/30">
                  历史 {historicalVariations.length} 道
                </Badge>
              )}
            </DialogTitle>
          </DialogHeader>

          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <span className="text-sm text-[#626a72]">目标难度：</span>
              <div className="flex gap-1">
                {[
                  { id: 'same', label: '相同' },
                  { id: 'easier', label: '更简单' },
                  { id: 'harder', label: '更难' },
                  { id: 'mixed', label: '混合' },
                ].map((option) => (
                  <Button
                    key={option.id}
                    variant={variationDifficulty === option.id ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setVariationDifficulty(option.id as typeof variationDifficulty)}
                    className={
                      variationDifficulty === option.id
                        ? 'bg-[#0070a0] hover:bg-[#005580] text-white'
                        : 'text-[#626a72]'
                    }
                  >
                    {option.label}
                  </Button>
                ))}
              </div>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={handleRegenerateVariations}
              disabled={generateVariations.isPending}
            >
              {generateVariations.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                  生成中...
                </>
              ) : (
                <>
                  <RefreshCw className="w-4 h-4 mr-1" />
                  重新生成
                </>
              )}
            </Button>
          </div>

          {isLoadingVariations || generateVariations.isPending ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 text-[#0070a0] animate-spin mr-2" />
              <span className="text-[#626a72]">
                {isLoadingVariations ? '加载历史变式题...' : 'AI 生成中...'}
              </span>
            </div>
          ) : displayedVariations.length === 0 ? (
            <div className="text-center py-12">
              <p className="text-[#626a72] mb-4">暂无变式题</p>
              <Button
                onClick={handleRegenerateVariations}
                disabled={generateVariations.isPending}
                className="bg-[#0070a0] hover:bg-[#005580]"
              >
                {generateVariations.isPending ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                    生成中...
                  </>
                ) : (
                  '立即生成'
                )}
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              {displayedVariations.map((variation, index) => (
                <div key={variation.id} className="bg-[#f7f9fa] border border-[#dee5eb] rounded-lg p-4">
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <p className="text-sm font-medium text-[#626a72]">变式题 {index + 1}</p>
                        <Badge
                          variant="outline"
                          className={{
                            easy: 'bg-[#d1fae5] text-[#10b981] border-[#10b981]/30',
                            medium: 'bg-[#fef3c7] text-[#f59e0b] border-[#f59e0b]/30',
                            hard: 'bg-[#ffe4e6] text-[#f43f5e] border-[#f43f5e]/30',
                          }[variation.difficulty]}
                        >
                          {DIFFICULTIES.find((d) => d.id === variation.difficulty)?.label || variation.difficulty}
                        </Badge>
                      </div>
                      <p className="text-[#1f1f1f] whitespace-pre-wrap mb-2">{variation.content}</p>
                    </div>
                    <div className="flex gap-1">
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-8 w-8 p-0"
                        onClick={() => collectVariation.mutate(variation.id)}
                        disabled={collectVariation.isPending}
                        title="收藏到错题本"
                      >
                        <Bookmark className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-8 w-8 p-0"
                        onClick={() => feedbackVariation.mutate({ id: variation.id, status: 'valid' })}
                        disabled={feedbackVariation.isPending}
                        title="题目合理"
                      >
                        <ThumbsUp className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-8 w-8 p-0"
                        onClick={() => feedbackVariation.mutate({ id: variation.id, status: 'invalid' })}
                        disabled={feedbackVariation.isPending}
                        title="题目不合理"
                      >
                        <ThumbsDown className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-8 w-8 p-0 text-[#f43f5e] hover:text-[#f43f5e]"
                        onClick={() => {
                          if (confirm('确定要删除这道变式题吗？')) {
                            deleteVariation.mutate(variation.id)
                          }
                        }}
                        disabled={deleteVariation.isPending}
                        title="删除"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>

                  <Button
                    variant="ghost"
                    size="sm"
                    className="text-[#0070a0] hover:text-[#004968]"
                    onClick={() =>
                      setExpandedVariationId(
                        expandedVariationId === variation.id ? null : variation.id
                      )
                    }
                  >
                    {expandedVariationId === variation.id ? '隐藏答案' : '查看答案'}
                  </Button>

                  {expandedVariationId === variation.id && (
                    <div className="mt-2 space-y-2">
                      <div>
                        <p className="text-sm font-medium text-[#626a72]">答案：</p>
                        <p className="text-[#1f1f1f] bg-[#d1fae5]/30 p-2 rounded">{variation.answer}</p>
                      </div>
                      {variation.explanation && (
                        <div>
                          <p className="text-sm font-medium text-[#626a72]">解析：</p>
                          <p className="text-[#626a72] bg-[#cce5f3]/30 p-2 rounded whitespace-pre-wrap">
                            {variation.explanation}
                          </p>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* 错因分析编辑弹框 */}
      <Dialog open={isEditingAnalysis} onOpenChange={setIsEditingAnalysis}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Brain className="w-5 h-5 text-[#0070a0]" />
              编辑错因分析
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-4">
            <div>
              <p className="text-sm font-medium text-[#1f1f1f] mb-2">错因标签</p>
              <div className="flex flex-wrap gap-2 mb-2">
                {MISTAKE_REASONS.map((reason) => {
                  const selected = editingTags.includes(reason.id)
                  return (
                    <Button
                      key={reason.id}
                      variant={selected ? 'default' : 'outline'}
                      size="sm"
                      onClick={() => toggleEditingTag(reason.id)}
                      className={selected ? 'text-white' : 'text-[#626a72]'}
                      style={
                        selected
                          ? { backgroundColor: reason.color, borderColor: reason.color }
                          : undefined
                      }
                    >
                      {reason.label}
                    </Button>
                  )
                })}
              </div>

              <div className="flex gap-2">
                <Input
                  placeholder="输入自定义标签，按回车添加"
                  value={customTagInput}
                  onChange={(e) => setCustomTagInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault()
                      addCustomTag()
                    }
                  }}
                  className="flex-1"
                />
                <Button variant="outline" size="sm" onClick={addCustomTag}>
                  添加
                </Button>
              </div>

              {editingTags.length > 0 && (
                <div className="flex flex-wrap gap-1 mt-2">
                  {editingTags.map((tag) => {
                    const tagColor = MISTAKE_REASONS.find((r) => r.id === tag)?.color || '#f43f5e'
                    return (
                      <Badge
                        key={tag}
                        variant="outline"
                        className="cursor-pointer text-xs text-white border-white/30"
                        style={{ backgroundColor: tagColor }}
                        onClick={() => removeEditingTag(tag)}
                      >
                        {tag}
                        <X className="w-3 h-3 ml-1" />
                      </Badge>
                    )
                  })}
                </div>
              )}
            </div>

            <div>
              <p className="text-sm font-medium text-[#1f1f1f] mb-2">详细分析</p>
              <textarea
                value={editingDetail}
                onChange={(e) => setEditingDetail(e.target.value)}
                placeholder="描述错因详情..."
                rows={3}
                className="w-full px-3 py-2 text-sm rounded-md border border-[#dee5eb] bg-white text-[#1f1f1f] placeholder:text-[#626a72] focus:outline-none focus:ring-2 focus:ring-[#0070a0] focus:border-transparent resize-none"
              />
            </div>

            <div>
              <p className="text-sm font-medium text-[#1f1f1f] mb-2">改进建议</p>
              <textarea
                value={editingAdvice}
                onChange={(e) => setEditingAdvice(e.target.value)}
                placeholder="输入改进建议..."
                rows={3}
                className="w-full px-3 py-2 text-sm rounded-md border border-[#dee5eb] bg-white text-[#1f1f1f] placeholder:text-[#626a72] focus:outline-none focus:ring-2 focus:ring-[#0070a0] focus:border-transparent resize-none"
              />
            </div>

            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setIsEditingAnalysis(false)}>
                取消
              </Button>
              <Button
                onClick={handleSaveAnalysis}
                disabled={updateQuestion.isPending}
                className="bg-[#0070a0] hover:bg-[#005580] text-white"
              >
                {updateQuestion.isPending ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                    保存中...
                  </>
                ) : (
                  '保存'
                )}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* 底部信息 */}
      <div className="flex items-center justify-between text-xs text-[#626a72]">
        <div className="flex items-center gap-4">
          <span>复习 {question.review_count} 次</span>
          {question.last_reviewed && (
            <span>
              最近复习：{formatDistanceToNow(question.last_reviewed)}
            </span>
          )}
        </div>
        <span>{formatDistanceToNow(question.created_at)}</span>
      </div>
    </div>
  )
}
