import type { Species } from './types'

export const SPECIES: Species[] = [
  {
    id: 'neon-tetra',
    nameZh: '霓虹灯鱼',
    nameLatin: 'Paracheirodon innesi',
    adultSizeCm: 4,
    bioload: 0.6,
    tempMin: 22,
    tempMax: 26,
    pHMin: 5.5,
    pHMax: 7.0,
    ghMin: 1,
    ghMax: 10,
    temperament: 'peaceful',
    profile: 'soft-acid',
    layer: 'mid',
    minGroup: 8,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#1ad1ff',
    accent: '#e11d48',
  },
  {
    id: 'cardinal-tetra',
    nameZh: '宝莲灯',
    nameLatin: 'Paracheirodon axelrodi',
    adultSizeCm: 5,
    bioload: 0.7,
    tempMin: 23,
    tempMax: 27,
    pHMin: 5.0,
    pHMax: 6.8,
    ghMin: 1,
    ghMax: 8,
    temperament: 'peaceful',
    profile: 'soft-acid',
    layer: 'mid',
    minGroup: 8,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: true,
    color: '#38bdf8',
    accent: '#dc2626',
  },
  {
    id: 'ember-tetra',
    nameZh: '铜钱灯 / 余烬灯',
    nameLatin: 'Hyphessobrycon amandae',
    adultSizeCm: 2.2,
    bioload: 0.25,
    tempMin: 23,
    tempMax: 27,
    pHMin: 5.5,
    pHMax: 7.0,
    ghMin: 1,
    ghMax: 8,
    temperament: 'peaceful',
    profile: 'soft-acid',
    layer: 'mid',
    minGroup: 8,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#f97316',
    accent: '#9a3412',
  },
  {
    id: 'harlequin',
    nameZh: '三角灯 / 异形鱊',
    nameLatin: 'Trigonostigma heteromorpha',
    adultSizeCm: 5,
    bioload: 0.7,
    tempMin: 22,
    tempMax: 27,
    pHMin: 6.0,
    pHMax: 7.5,
    ghMin: 2,
    ghMax: 15,
    temperament: 'peaceful',
    profile: 'soft-acid',
    layer: 'mid',
    minGroup: 6,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#fb7185',
    accent: '#1e293b',
  },
  {
    id: 'guppy',
    nameZh: '孔雀鱼',
    nameLatin: 'Poecilia reticulata',
    adultSizeCm: 5,
    bioload: 0.8,
    tempMin: 22,
    tempMax: 28,
    pHMin: 7.0,
    pHMax: 8.2,
    ghMin: 8,
    ghMax: 20,
    temperament: 'peaceful',
    profile: 'neutral',
    layer: 'top',
    minGroup: 3,
    finNipper: false,
    longFins: true,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#a855f7',
    accent: '#facc15',
  },
  {
    id: 'molly',
    nameZh: '玛丽鱼',
    nameLatin: 'Poecilia sphenops',
    adultSizeCm: 8,
    bioload: 1.4,
    tempMin: 24,
    tempMax: 28,
    pHMin: 7.5,
    pHMax: 8.5,
    ghMin: 15,
    ghMax: 30,
    temperament: 'peaceful',
    profile: 'hard-alkaline',
    layer: 'mid',
    minGroup: 3,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#111827',
    accent: '#67e8f9',
  },
  {
    id: 'betta',
    nameZh: '暹罗斗鱼',
    nameLatin: 'Betta splendens',
    adultSizeCm: 7,
    bioload: 1.0,
    tempMin: 24,
    tempMax: 30,
    pHMin: 6.5,
    pHMax: 7.5,
    ghMin: 5,
    ghMax: 15,
    temperament: 'aggressive',
    profile: 'neutral',
    layer: 'top',
    minGroup: 1,
    finNipper: false,
    longFins: true,
    eatsSmallFish: false,
    eatsShrimp: true,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#ef4444',
    accent: '#1d4ed8',
  },
  {
    id: 'angel',
    nameZh: '神仙鱼',
    nameLatin: 'Pterophyllum scalare',
    adultSizeCm: 15,
    bioload: 2.4,
    tempMin: 24,
    tempMax: 30,
    pHMin: 6.0,
    pHMax: 7.5,
    ghMin: 3,
    ghMax: 12,
    temperament: 'semi-aggressive',
    profile: 'soft-acid',
    layer: 'mid',
    minGroup: 1,
    finNipper: false,
    longFins: true,
    eatsSmallFish: true,
    eatsShrimp: true,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#e5e7eb',
    accent: '#111827',
  },
  {
    id: 'tiger-barb',
    nameZh: '虎皮鱼',
    nameLatin: 'Puntigrus tetrazona',
    adultSizeCm: 7,
    bioload: 1.2,
    tempMin: 20,
    tempMax: 26,
    pHMin: 6.0,
    pHMax: 7.5,
    ghMin: 4,
    ghMax: 15,
    temperament: 'semi-aggressive',
    profile: 'neutral',
    layer: 'mid',
    minGroup: 6,
    finNipper: true,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: true,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#f59e0b',
    accent: '#111827',
  },
  {
    id: 'goldfish',
    nameZh: '兰寿金鱼',
    nameLatin: 'Carassius auratus',
    adultSizeCm: 18,
    bioload: 5.5,
    tempMin: 10,
    tempMax: 22,
    pHMin: 7.0,
    pHMax: 8.2,
    ghMin: 6,
    ghMax: 20,
    temperament: 'peaceful',
    profile: 'cold',
    layer: 'mid',
    minGroup: 1,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: true,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#f97316',
    accent: '#ffffff',
  },
  {
    id: 'discus',
    nameZh: '七彩神仙',
    nameLatin: 'Symphysodon aequifasciatus',
    adultSizeCm: 18,
    bioload: 3.2,
    tempMin: 28,
    tempMax: 30.5,
    pHMin: 5.5,
    pHMax: 6.8,
    ghMin: 1,
    ghMax: 6,
    temperament: 'peaceful',
    profile: 'soft-acid',
    layer: 'mid',
    minGroup: 4,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: true,
    color: '#f472b6',
    accent: '#7c3aed',
  },
  {
    id: 'ram',
    nameZh: '德国蓝羊',
    nameLatin: 'Mikrogeophagus ramirezi',
    adultSizeCm: 5,
    bioload: 0.8,
    tempMin: 26,
    tempMax: 30,
    pHMin: 5.5,
    pHMax: 7.0,
    ghMin: 1,
    ghMax: 10,
    temperament: 'semi-aggressive',
    profile: 'soft-acid',
    layer: 'bottom',
    minGroup: 2,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: true,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: true,
    color: '#3b82f6',
    accent: '#facc15',
  },
  {
    id: 'yellow-lab',
    nameZh: '黄线立 / 马鲷',
    nameLatin: 'Labidochromis caeruleus',
    adultSizeCm: 10,
    bioload: 1.8,
    tempMin: 23,
    tempMax: 28,
    pHMin: 7.8,
    pHMax: 8.6,
    ghMin: 10,
    ghMax: 20,
    temperament: 'aggressive',
    profile: 'hard-alkaline',
    layer: 'mid',
    minGroup: 1,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: true,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#fde047',
    accent: '#1e3a8a',
  },
  {
    id: 'cory-panda',
    nameZh: '熊猫鼠',
    nameLatin: 'Corydoras panda',
    adultSizeCm: 5,
    bioload: 0.7,
    tempMin: 21,
    tempMax: 25,
    pHMin: 6.0,
    pHMax: 7.5,
    ghMin: 2,
    ghMax: 12,
    temperament: 'peaceful',
    profile: 'soft-acid',
    layer: 'bottom',
    minGroup: 6,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#e7e5e4',
    accent: '#171717',
  },
  {
    id: 'bristlenose',
    nameZh: '异型清道夫',
    nameLatin: 'Ancistrus cf. cirrhosus',
    adultSizeCm: 12,
    bioload: 2.0,
    tempMin: 22,
    tempMax: 28,
    pHMin: 6.5,
    pHMax: 7.8,
    ghMin: 4,
    ghMax: 20,
    temperament: 'peaceful',
    profile: 'neutral',
    layer: 'bottom',
    minGroup: 1,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: true,
    sensitive: false,
    color: '#57534e',
    accent: '#a8a29e',
  },
  {
    id: 'oto',
    nameZh: '小精灵 / 奥托',
    nameLatin: 'Otocinclus vittatus',
    adultSizeCm: 4,
    bioload: 0.4,
    tempMin: 22,
    tempMax: 26,
    pHMin: 6.0,
    pHMax: 7.5,
    ghMin: 4,
    ghMax: 15,
    temperament: 'peaceful',
    profile: 'soft-acid',
    layer: 'bottom',
    minGroup: 4,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: true,
    sensitive: true,
    color: '#a3a3a3',
    accent: '#171717',
  },
  {
    id: 'kuhli',
    nameZh: '泥鳅 / 库里鳅',
    nameLatin: 'Pangio kuhlii',
    adultSizeCm: 10,
    bioload: 0.8,
    tempMin: 24,
    tempMax: 28,
    pHMin: 5.5,
    pHMax: 7.0,
    ghMin: 2,
    ghMax: 10,
    temperament: 'peaceful',
    profile: 'soft-acid',
    layer: 'bottom',
    minGroup: 4,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#b45309',
    accent: '#1c1917',
  },
  {
    id: 'gourami',
    nameZh: '珍珠马甲 / 矮曼龙',
    nameLatin: 'Trichogaster lalius',
    adultSizeCm: 7,
    bioload: 1.1,
    tempMin: 22,
    tempMax: 28,
    pHMin: 6.0,
    pHMax: 7.5,
    ghMin: 4,
    ghMax: 15,
    temperament: 'semi-aggressive',
    profile: 'soft-acid',
    layer: 'top',
    minGroup: 1,
    finNipper: false,
    longFins: true,
    eatsSmallFish: false,
    eatsShrimp: true,
    isShrimp: false,
    isSnail: false,
    algaeEater: false,
    sensitive: false,
    color: '#fb7185',
    accent: '#22d3ee',
  },
  {
    id: 'amano',
    nameZh: '大和藻虾',
    nameLatin: 'Caridina multidentata',
    adultSizeCm: 4,
    bioload: 0.2,
    tempMin: 20,
    tempMax: 27,
    pHMin: 6.5,
    pHMax: 7.5,
    ghMin: 4,
    ghMax: 12,
    temperament: 'peaceful',
    profile: 'neutral',
    layer: 'bottom',
    minGroup: 4,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: true,
    isSnail: false,
    algaeEater: true,
    sensitive: false,
    color: '#d6d3d1',
    accent: '#44403c',
  },
  {
    id: 'cherry-shrimp',
    nameZh: '樱桃虾',
    nameLatin: 'Neocaridina davidi',
    adultSizeCm: 2.5,
    bioload: 0.12,
    tempMin: 20,
    tempMax: 27,
    pHMin: 6.5,
    pHMax: 8.0,
    ghMin: 4,
    ghMax: 14,
    temperament: 'peaceful',
    profile: 'neutral',
    layer: 'bottom',
    minGroup: 6,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: true,
    isSnail: false,
    algaeEater: true,
    sensitive: false,
    color: '#e11d48',
    accent: '#fecdd3',
  },
  {
    id: 'nerite',
    nameZh: '斑马螺',
    nameLatin: 'Neritina natalensis',
    adultSizeCm: 2.5,
    bioload: 0.15,
    tempMin: 22,
    tempMax: 28,
    pHMin: 7.0,
    pHMax: 8.2,
    ghMin: 8,
    ghMax: 20,
    temperament: 'peaceful',
    profile: 'hard-alkaline',
    layer: 'bottom',
    minGroup: 1,
    finNipper: false,
    longFins: false,
    eatsSmallFish: false,
    eatsShrimp: false,
    isShrimp: false,
    isSnail: true,
    algaeEater: true,
    sensitive: false,
    color: '#292524',
    accent: '#fef3c7',
  },
]

const SPECIES_MAP = new Map(SPECIES.map((s) => [s.id, s]))

export function getSpecies(id: string): Species | undefined {
  return SPECIES_MAP.get(id)
}

export function requireSpecies(id: string): Species {
  const species = SPECIES_MAP.get(id)
  if (!species) {
    throw new Error(`Unknown species: ${id}`)
  }
  return species
}
